### ISSUE TITLE
When I use hotkey to call my starred note, some error comes

### ISSUE THREAD

**Issue by Quorafind** [Vinzent03/obsidian-shortcuts-for-starred-files#1]
It will create the file I had deleted before, and then open the file as usual.(BTW, when I use CTRL+R to refresh obsidian.

The generated file would be starred. I had used safe mode to close other plugins. But I do not know why.

**Comment by Vinzent03** [comment]
Thanks for the tip. But its actually a mistake from the developers. If you delete a starred file it is still in the sidebar right? And if you reload, the note is gone from the sidebar as you expect. But internally the note is still there and saved as a starred note. I will ask in Discord why this is happening.

**Comment by Quorafind** [comment]
@Vinzent03 Hmmm, no, when I reload obsidian, starred files that I unstarred disappeared . But when using starred shortcut plugin, the console would output some of them. one of them is generated and it would be starred after I refreshed the obsidian

**Comment by Vinzent03** [comment]
What do you mean with `generated` ? Was the tile starred and then deleted from you?

**Comment by Quorafind** [comment]
Yep. And `generated` means that a blank note with a title that I ever starred would be generated after use hotkey to call the starred stuff.

**Comment by Vinzent03** [comment]
Yeah thats right. Internal the deleted file is still starred, so my plugin opens it, why Obsidian creates an empty file. In the moment you can unstar the file manually and then delete it. Then it is gone from the starred list.

**Comment by Quorafind** [comment]
Ok, but my starred list is full of `Starred then Deleted` files, and dont know how to clear it LOL😂

**Comment by Vinzent03** [comment]
Yeah I thought the same when I discoverd that bug. I will wait for an answer from the devs. If they dont plan to fix that, I will add a fix later today. (If it works what I am currently thinking about)

**Comment by Vinzent03** [comment]
I forgot to remove a ´console.log()` in the plugin. If you expand that list in the console, you see under length how many files you have starred some time vs you have currently starred.
