### ISSUE TITLE
Allow opening saved/starred searches

### ISSUE THREAD

**Issue by AngelusDomini** [Vinzent03/obsidian-shortcuts-for-starred-files#2]
Do you have plans for implementing this? Whenever I open one of my saved searches, the plugin just shows a notification that index x is a starred search—I'm assuming you did this on purpose, so there's probably a reason you haven't included this.
For my use case, my most opened starred "file" is a saved search. I would think it's doable to let the plugin open the starred search in Obsidian's Search plugin, as it normally does without the plugin.

**Comment by Vinzent03** [comment]
I will look into it. I don't know if I can set a search...

**Comment by Vinzent03** [comment]
New release is out! I hope it works seamlessly.

**Comment by AngelusDomini** [comment]
Thank you so much! It seems to be working seamlessly 😁
