### ISSUE TITLE
Support cycle through starred files with hotkey

### ISSUE THREAD

**Issue by wenlzhang** [Vinzent03/obsidian-shortcuts-for-starred-files#4]
In my use case, the plugin [Vinzent03/obsidian-hotkeys-for-specific-files](https://github.com/Vinzent03/obsidian-hotkeys-for-specific-files) is used for setting hotkeys for fixed files, e.g. one for the GTD Next Actions page and one for the GTD Waiting For page, and this plugin is used for frequently used files during a period of time.

For instance, within the coming four weeks, I may work on five projects. To this end, I may star the five files which correspond to the five project pages. Since these starred files/projects would change when these projects are completed, it may be unnecessary to remember which hotkey corresponds to which project page. Therefore, it would be great if there can be a hotkey for cycling through the set starred files. Specifically, the hotkey may be set as follows:
- One selects in the plugin setting page how many, e.g. 5, instead of all starred files, starred files to cycle through
- One sets a hotkey for the cycling through command
- One uses the hotkey to cycle through/open the 5 starred files in the currently active pane

**Comment by Vinzent03** [comment]
I don't have the time to implement this in the next weeks. But I think the best solution is to set the hotkey for starred files to `Ctrl` + `<1-9>`. Then you can cycle through the list by typing from 0 to 5 with `Ctrl` pressed.
