### ISSUE TITLE
Support for bookmarks?

### ISSUE THREAD

**Issue by tonyxiao** [Vinzent03/obsidian-shortcuts-for-starred-files#5]
Starred plugin is getting deprecated and the replacement is the bookmarks plugin. Can this plugin be reworked to support bookmarks too?

**Comment by tonyxiao** [comment]
@Vinzent03

**Comment by Vinzent03** [comment]
No need for another ping.
I've migrated the plugin now to bookmarks. I think there is a lot to improve to really take the full power of bookmarks, but for now the old behavior works again. Enjoy 1.0.0

**Comment by tonyxiao** [comment]
Yay thank you! What do you have in mind in terms of improvements to take full power of bookmarks?

**Comment by Vinzent03** [comment]
I don't take advantage of the grouping in any form. I think it may even break the plugin a bit.

**Comment by tonyxiao** [comment]
you mean the fact that you can now create folder out of bookmarks right?

**Comment by Vinzent03** [comment]
Yeah you can create your own groups of bookmarks.
